"""Données de démo : 1 admin (admin@salon.com / change-me-123) + 25 produits réalistes."""
from typing import Any, Dict, List

DEMO_ADMIN_USERNAME = "admin@salon.com"
DEMO_ADMIN_PASSWORD = "change-me-123"

DEMO_PRODUCTS: List[Dict[str, Any]] = [
    {"name": "Shampooing Hydratant", "brand": "Kérastase", "price": 28.90, "category": "shampoo", "description": "Nourrit et répare les pointes abîmées.", "image_url": None, "tags": {"hair_types": ["1A", "1B", "1C", "2A"], "concerns": ["dry", "damaged"], "porosity": ["high", "medium"], "goals": ["hydrate", "repair"], "scalp": ["normal"]}},
    {"name": "Masque Réparation Intense", "brand": "Kérastase", "price": 42.00, "category": "mask", "description": "Reconstruit la fibre en profondeur.", "image_url": None, "tags": {"hair_types": ["all"], "concerns": ["damaged", "dry"], "porosity": ["high"], "goals": ["repair", "hydrate"], "scalp": ["normal"]}},
    {"name": "Huile Elixir Ultime", "brand": "Kérastase", "price": 38.50, "category": "oil", "description": "Brillance et discipline des pointes.", "image_url": None, "tags": {"hair_types": ["1A", "1B", "2A", "2B"], "concerns": ["frizz", "dry"], "porosity": ["low", "medium"], "goals": ["hydrate"], "scalp": ["normal"]}},
    {"name": "Shampooing Volume", "brand": "Redken", "price": 24.90, "category": "shampoo", "description": "Donne du corps aux cheveux fins.", "image_url": None, "tags": {"hair_types": ["1A", "1B", "1C"], "concerns": ["fine", "flat"], "porosity": ["medium"], "goals": ["volume"], "scalp": ["normal"]}},
    {"name": "After-Shampooing Volume", "brand": "Redken", "price": 26.90, "category": "conditioner", "description": "Gainant sans alourdir.", "image_url": None, "tags": {"hair_types": ["1A", "1B"], "concerns": ["fine"], "porosity": ["medium"], "goals": ["volume"], "scalp": ["normal"]}},
    {"name": "Shampooing Sans Sulfate Color Protect", "brand": "Redken", "price": 26.90, "category": "shampoo", "description": "Préserve l'éclat des couleurs.", "image_url": None, "tags": {"hair_types": ["all"], "concerns": ["color_treated"], "porosity": ["medium"], "goals": ["hydrate"], "scalp": ["normal"]}},
    {"name": "Masque Boucles Définies", "brand": "Moroccanoil", "price": 41.50, "category": "mask", "description": "Nutrition intense pour boucles 3B-4A.", "image_url": None, "tags": {"hair_types": ["3B", "3C", "4A"], "concerns": ["dry", "frizz"], "porosity": ["high"], "goals": ["curl", "hydrate"], "scalp": ["normal"]}},
    {"name": "Huile de soin", "brand": "Moroccanoil", "price": 44.00, "category": "oil", "description": "Lissant et brillant, toutes natures.", "image_url": None, "tags": {"hair_types": ["all"], "concerns": ["frizz", "dry"], "porosity": ["low", "medium"], "goals": ["hydrate"], "scalp": ["normal"]}},
    {"name": "Shampooing Hydratant", "brand": "Moroccanoil", "price": 27.00, "category": "shampoo", "description": "Hydratation légère pour usage fréquent.", "image_url": None, "tags": {"hair_types": ["2A", "2B", "2C", "3A"], "concerns": ["dry"], "porosity": ["medium"], "goals": ["hydrate"], "scalp": ["normal"]}},
    {"name": "Soin Anti-Chute Densifique", "brand": "Kérastase", "price": 52.00, "category": "treatment", "description": "Renforce et densifie la chevelure.", "image_url": None, "tags": {"hair_types": ["all"], "concerns": ["hair_loss", "fine"], "porosity": ["medium"], "goals": ["repair"], "scalp": ["normal", "dry"]}},
    {"name": "Conditioner Hydratant Quotidien", "brand": "Olaplex", "price": 28.00, "category": "conditioner", "description": "Réparation des liaisons disulfures.", "image_url": None, "tags": {"hair_types": ["all"], "concerns": ["damaged", "color_treated"], "porosity": ["high"], "goals": ["repair"], "scalp": ["normal"]}},
    {"name": "Masque Réparateur Olaplex No.3", "brand": "Olaplex", "price": 32.00, "category": "mask", "description": "Traitement réparateur à la maison.", "image_url": None, "tags": {"hair_types": ["all"], "concerns": ["damaged"], "porosity": ["high", "medium"], "goals": ["repair"], "scalp": ["normal"]}},
    {"name": "Sérum Anti-Frisottis", "brand": "Wella", "price": 22.90, "category": "oil", "description": "Lisse et protège contre l'humidité.", "image_url": None, "tags": {"hair_types": ["2A", "2B", "2C", "3A"], "concerns": ["frizz"], "porosity": ["medium"], "goals": ["hydrate"], "scalp": ["normal"]}},
    {"name": "Shampooing Purifiant", "brand": "Wella", "price": 18.90, "category": "shampoo", "description": "Nettoie en douceur le cuir chevelu.", "image_url": None, "tags": {"hair_types": ["all"], "concerns": ["flat"], "porosity": ["medium"], "goals": ["volume"], "scalp": ["oily", "normal"]}},
    {"name": "Masque Cuir chevelu", "brand": "Kérastase", "price": 45.00, "category": "treatment", "description": "Soin du cuir chevelu sensible.", "image_url": None, "tags": {"hair_types": ["all"], "concerns": [], "porosity": ["all"], "goals": ["hydrate"], "scalp": ["dry", "sensitive"]}},
    {"name": "Baume Leave-in", "brand": "Redken", "price": 29.90, "category": "treatment", "description": "Protection thermique et brillance.", "image_url": None, "tags": {"hair_types": ["all"], "concerns": ["damaged"], "porosity": ["high"], "goals": ["repair"], "scalp": ["normal"]}},
    {"name": "Shampooing Douceur", "brand": "L'Oréal Pro", "price": 14.90, "category": "shampoo", "description": "Doux pour usage quotidien.", "image_url": None, "tags": {"hair_types": ["1A", "1B", "2A"], "concerns": [], "porosity": ["low"], "goals": ["hydrate"], "scalp": ["normal"]}},
    {"name": "Après-shampooing Douceur", "brand": "L'Oréal Pro", "price": 15.90, "category": "conditioner", "description": "Démêlage et douceur.", "image_url": None, "tags": {"hair_types": ["1A", "1B", "2A"], "concerns": ["dry"], "porosity": ["medium"], "goals": ["hydrate"], "scalp": ["normal"]}},
    {"name": "Huile Sublime", "brand": "L'Oréal Pro", "price": 19.90, "category": "oil", "description": "Brillance sans effet gras.", "image_url": None, "tags": {"hair_types": ["all"], "concerns": ["frizz"], "porosity": ["low"], "goals": ["hydrate"], "scalp": ["normal"]}},
    {"name": "Masque 7 secondes", "brand": "L'Oréal Pro", "price": 24.90, "category": "mask", "description": "Rinçage instantané, effet soyeux.", "image_url": None, "tags": {"hair_types": ["2A", "2B", "2C", "3A"], "concerns": ["dry", "frizz"], "porosity": ["medium"], "goals": ["hydrate"], "scalp": ["normal"]}},
    {"name": "Shampooing Boucles", "brand": "Shea Moisture", "price": 16.90, "category": "shampoo", "description": "Spécifique boucles et crépus.", "image_url": None, "tags": {"hair_types": ["3B", "3C", "4A", "4B"], "concerns": ["dry"], "porosity": ["high"], "goals": ["curl", "hydrate"], "scalp": ["normal"]}},
    {"name": "Masque Karité", "brand": "Shea Moisture", "price": 18.90, "category": "mask", "description": "Nutrition intense au karité.", "image_url": None, "tags": {"hair_types": ["3B", "3C", "4A"], "concerns": ["dry", "damaged"], "porosity": ["high"], "goals": ["hydrate", "repair"], "scalp": ["normal"]}},
    {"name": "Gel Définition Boucles", "brand": "Cantu", "price": 12.90, "category": "treatment", "description": "Définit et fixe les boucles.", "image_url": None, "tags": {"hair_types": ["3A", "3B", "3C"], "concerns": ["frizz"], "porosity": ["medium"], "goals": ["curl"], "scalp": ["normal"]}},
    {"name": "Shampooing Équilibre", "brand": "Bioderma", "price": 14.50, "category": "shampoo", "description": "Cuir chevelu et longueurs équilibrés.", "image_url": None, "tags": {"hair_types": ["all"], "concerns": [], "porosity": ["all"], "goals": ["hydrate"], "scalp": ["oily", "normal"]}},
    {"name": "Sérum Croissance", "brand": "Kérastase", "price": 48.00, "category": "treatment", "description": "Stimule et fortifie la pousse.", "image_url": None, "tags": {"hair_types": ["all"], "concerns": ["hair_loss"], "porosity": ["medium"], "goals": ["repair"], "scalp": ["normal"]}},
    {"name": "Spray Protecteur Thermique", "brand": "Redken", "price": 26.00, "category": "treatment", "description": "Protège jusqu'à 230°C.", "image_url": None, "tags": {"hair_types": ["all"], "concerns": ["damaged"], "porosity": ["all"], "goals": ["repair"], "scalp": ["normal"]}},
]
